### ISSUE TITLE
Changes to the ansible playbook

### ISSUE THREAD

**Issue by pereriksson** [dbwebb-se/microblog#16]
# Two-factor authentication
If two-factor authentication is enabled for the Azure account, the `~/.azure/credentials` login method cannot be used. Login is required to use the Azure CLI with `az login`. If the `credentials` file is present it takes presence over the CLI, causing login to fail.

# DNS Zone
A DNS Zone is required to add DNS records for a domain.
In `create_instance.yml`:
```
-   name: Create a DNS Zone
    azure_rm_dnszone:
        resource_group: "{{ resource_group }}"
        name: "{{ domain_name }}"
        tags: "{{ vmtags }}"
        
-   name: Ensure "A" records for loadBalancer
    azure_rm_dnsrecordset:
...
```
In `remove_instance.yml`:
```
-   name: Delete a DNS Zone
    azure_rm_dnszone:
        resource_group: "{{ resource_group }}"
        name: "{{ domain_name }}"
        state: absent

```
